defaults: &defaults
  api:
    port: 3100
    # longer topics are possible, shorter ones too
    maxContentLengthTopic: 256
    # all other inputs can be:
    maxContentLength: 512
    # maximale messages per dialog
    maxMessages: 25
    # topic rule, default: two topics per day
    topicInterval: 1
    topicLimit: 2
    # for uni-color edges
    dominantColorScheme: true

  logger:
    name: dpt-server
    level: debug
    levels:
      trace:
      debug: STDOUT
      info:
      warn:
      error: STDERR
      fatal:

development:
  <<: *defaults
  dbUrl: mongodb+srv://devpatrick:polarizer@testdpt.wfj1w.mongodb.net/test
#  dbUrl: mongodb://localhost/dpt-dev

production:
  <<: *defaults
  dbUrl: mongodb+srv://devpatrick:polarizer@testdpt.wfj1w.mongodb.net/test

  logger:
    level: debug
    levels:
      trace:
      debug: STDOUT
      info: ./log/info.log
      warn: ./log/warn.log
      error: ./log/error.log
      fatal: ./log/fatal.log
